// tools/compat/angular/angular-19/src/main.ts
import { provideAppInitializer } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { setAssetPath } from '@parlamentsdienste/pdcomponents-core/components';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent, {
    providers: [
        provideAppInitializer(() => {
            setAssetPath('http://localhost:4200');
        }),
    ],
}).catch(error => console.error(error));

// apps/react-test/src/main.tsx
import { setAssetPath } from '@parlamentsdienste/pdcomponents-core/components';
import '@parlamentsdienste/pdcomponents-core/styles/parlamentsdienstecore.css';
import '@parlamentsdienste/pdcomponents-core/styles/typography.css';
import * as ReactDOM from 'react-dom/client';
import App from './app/app';

setAssetPath('http://localhost:4200');

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);

root.render(
    // <StrictMode>
    <App />,
    // </StrictMode>,
);
